version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip3 install -r requirements.txt -t ./package

  build:
    commands:
      - echo Build started on `date`
      - python3 -m compileall .

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
