version: 0.2

phases:
  install:
    commands:
      - echo "Installing .NET SDK 8.0 on Amazon Linux 2023..."
      - sudo dnf install -y dotnet-sdk-8.0

  build:
    commands:
      - echo "Building the application..."
      - dotnet build -c Release

  post_build:
    commands:
      - echo "Build completed successfully."
artifacts:
  files:
    - '**/*'
  discard-paths: no
